//LastModifiedTime:504911232000000000
#pragma once
#include "Core/Reflection/Reflection.h"
#include "../../../../SDEngine\Core\Objects\Entities\Entity.h"


//Reflection for class Entity
REFLECT_CLASS_BEGIN(Entity)
REFLECT_CLASS_BEGIN_PARENTS()
REFLECT_CLASS_PARENT(EngineObject)
REFLECT_CLASS_PARENT_END()
REFLECT_CLASS_MEMBERS_BEGIN()
REFLECT_CLASS_MEMBER(LastFrameTransform, "Last Frame Transform", true, "Default")
REFLECT_CLASS_MEMBER(bVisible, "Visible", false, "Entity")
REFLECT_CLASS_MEMBER(bHiddenInGame, "Hidden In Game", false, "Entity")
REFLECT_CLASS_MEMBER(bNeedsTick, "Needs Tick", false, "Entity")
REFLECT_CLASS_MEMBER(bNeedsBeginPlay, "Needs Begin Play", false, "Entity")
REFLECT_CLASS_MEMBER(bCastShadows, "Cast Shadows", false, "Entity")
REFLECT_CLASS_MEMBER(Transform, "Transform", false, "Transform")
REFLECT_CLASS_MEMBERS_END()
REFLECT_CLASS_FUNCTION_BEGIN()
REFLECT_CLASS_FUNCTION(IsVisible, False, bool, 0, True)
REFLECT_CLASS_FUNCTION(SetVisibility, False, void, 0, False, {Show, bool, True, 1})
REFLECT_CLASS_FUNCTION(ToggleVisibility, False, void, 0, False)
REFLECT_CLASS_FUNCTION(IsHiddenInGame, False, bool, 0, True)
REFLECT_CLASS_FUNCTION(SetHiddenInGame, False, void, 0, False, {Hidden, bool, True, 1})
REFLECT_CLASS_FUNCTION(CastsShadows, False, bool, 0, True)
REFLECT_CLASS_FUNCTION(SetCastShadows, False, void, 0, False, {CastShadows, bool, True, 1})
REFLECT_CLASS_FUNCTION(GetLocation, True, Vector3D, 1, True)
REFLECT_CLASS_FUNCTION(GetRotation, True, Vector3D, 1, True)
REFLECT_CLASS_FUNCTION(GetScale, True, Vector3D, 1, True)
REFLECT_CLASS_FUNCTION(GetLinearVelocity, True, Vector3D, 0, True)
REFLECT_CLASS_FUNCTION(GetAngularVelocity, True, Vector3D, 0, True)
REFLECT_CLASS_FUNCTION(AddLocation, False, void, 0, False, {Offset, Vector3D, True, 0})
REFLECT_CLASS_FUNCTION(AddLocation, False, void, 0, False, {X, float, True, 1}, {Y, float, True, 1}, {Z, float, True, 1})
REFLECT_CLASS_FUNCTION(SetLocation, False, void, 0, False, {Location, Vector3D, True, 1})
REFLECT_CLASS_FUNCTION(SetLocation, False, void, 0, False, {X, float, True, 1}, {Y, float, True, 1}, {Z, float, True, 1})
REFLECT_CLASS_FUNCTION(AddRotation, False, void, 0, False, {RotationDelta, Vector3D, True, 1})
REFLECT_CLASS_FUNCTION(AddRotation, False, void, 0, False, {X, float, True, 1}, {Y, float, True, 1}, {Z, float, True, 1})
REFLECT_CLASS_FUNCTION(SetRotation, False, void, 0, False, {Rotation, Vector3D, True, 1})
REFLECT_CLASS_FUNCTION(SetRotation, False, void, 0, False, {X, float, True, 1}, {Y, float, True, 1}, {Z, float, True, 1})
REFLECT_CLASS_FUNCTION(AddScale, False, void, 0, False, {ScaleDelta, Vector3D, True, 1})
REFLECT_CLASS_FUNCTION(AddScale, False, void, 0, False, {X, float, True, 1}, {Y, float, True, 1}, {Z, float, True, 1})
REFLECT_CLASS_FUNCTION(SetScale, False, void, 0, False, {Scale, Vector3D, True, 1})
REFLECT_CLASS_FUNCTION(SetScale, False, void, 0, False, {X, float, True, 1}, {Y, float, True, 1}, {Z, float, True, 1})
REFLECT_CLASS_FUNCTION(SetUniformScale, False, void, 0, False, {Scale, float, True, 1})
REFLECT_CLASS_FUNCTION(GetTransform, True, FTransform, 1, True)
REFLECT_CLASS_FUNCTION(SetTransform, False, void, 0, False, {NewTransform, FTransform, True, 1})
REFLECT_CLASS_FUNCTION(GetLastFrameTransform, True, FTransform, 1, True)
REFLECT_CLASS_FUNCTION(SetLastFrameTransform, False, void, 0, False, {OldTransform, FTransform, True, 1})
REFLECT_CLASS_FUNCTION_END()
REFLECT_CLASS_END()
