#pragma once
#include "Core/Reflection/Reflection.h"
#include "../../../../SDEngine\Test\ReflectionTest.h"


//Reflection for struct FReflectionTest
REFLECT_STRUCT_BEGIN(FReflectionTest)
REFLECT_STRUCT_BEGIN_PARENTS()
REFLECT_STRUCT_PARENT_END()
RREFLECT_STRUCT_MEMBERS_BEGIN()
REFLECT_STRUCT_MEMBERS_END(testFloat)
REFLECT_STRUCT_MEMBERS_END(testString)
REFLECT_STRUCT_MEMBERS_END(testInt)
REFLECT_STRUCT_MEMBERS_END(testVector4D)
REFLECT_STRUCT_MEMBERS_END(testVector3D)
REFLECT_STRUCT_MEMBERS_END(testVector2D)
REFLECT_STRUCT_MEMBERS_END(testBool)
REFLECT_STRUCT_MEMBERS_END(boolArray)
RREFLECT_STRUCT_MEMBERS_BEGIN()
REFLECT_STRUCT_END()
