//LastModifiedTime:504911232000000000
#pragma once
#include "Core/Reflection/Reflection.h"
#include "../../../../SDEngine\Core\Objects\CoreTypes\StaticMesh.h"


//Reflection for class StaticMesh
REFLECT_CLASS_BEGIN(StaticMesh)
REFLECT_CLASS_BEGIN_PARENTS()
REFLECT_CLASS_PARENT(EngineObject)
REFLECT_CLASS_PARENT_END()
REFLECT_CLASS_MEMBERS_BEGIN()
REFLECT_CLASS_MEMBERS_END()
REFLECT_CLASS_FUNCTION_BEGIN()
REFLECT_CLASS_FUNCTION_END()
REFLECT_CLASS_END()
