#pragma once
#include "Core/Reflection/Reflection.h"
#include "./Core\Objects\Entities\Light.h"

//Reflection for struct FLightInfo
REFLECT_STRUCT_BEGIN(FLightInfo)
REFLECT_STRUCT_BEGIN_PARENTS()
REFLECT_STRUCT_PARENT_END()
REFLECT_STRUCT_MEMBERS_BEGIN()
REFLECT_STRUCT_MEMBER(Intensity)
REFLECT_STRUCT_MEMBER(Color)
REFLECT_STRUCT_MEMBER(Attenuation)
REFLECT_STRUCT_MEMBERS_END()
REFLECT_STRUCT_END()
//Reflection for struct Light
REFLECT_CLASS_BEGIN(Light)
REFLECT_CLASS_BEGIN_PARENTS()
REFLECT_CLASS_PARENT(Actor)
REFLECT_CLASS_PARENT_END()
REFLECT_CLASS_MEMBERS_BEGIN()
REFLECT_STRUCT_MEMBER(testVal)
REFLECT_STRUCT_MEMBER(LightInfo)
REFLECT_CLASS_MEMBERS_END()
REFLECT_CLASS_END()
