//LastModifiedTime:637194022260496026
#pragma once
#include "Core/Reflection/Reflection.h"
#include "./Core\Pictorum\PictorumDataTypes.h"


//Reflection for struct FFillRule
REFLECT_STRUCT_BEGIN(FFillRule)
REFLECT_STRUCT_BEGIN_PARENTS()
REFLECT_STRUCT_PARENT_END()
REFLECT_STRUCT_MEMBERS_BEGIN()
REFLECT_STRUCT_MEMBERS_END()
REFLECT_STRUCT_END()

//Reflection for struct FRenderGeometry
REFLECT_STRUCT_BEGIN(FRenderGeometry)
REFLECT_STRUCT_BEGIN_PARENTS()
REFLECT_STRUCT_PARENT_END()
REFLECT_STRUCT_MEMBERS_BEGIN()
REFLECT_STRUCT_MEMBERS_END()
REFLECT_STRUCT_END()

//Reflection for struct FAnchors
REFLECT_STRUCT_BEGIN(FAnchors)
REFLECT_STRUCT_BEGIN_PARENTS()
REFLECT_STRUCT_PARENT_END()
REFLECT_STRUCT_MEMBERS_BEGIN()
REFLECT_STRUCT_MEMBERS_END()
REFLECT_STRUCT_END()

//Reflection for struct FOffsets
REFLECT_STRUCT_BEGIN(FOffsets)
REFLECT_STRUCT_BEGIN_PARENTS()
REFLECT_STRUCT_PARENT_END()
REFLECT_STRUCT_MEMBERS_BEGIN()
REFLECT_STRUCT_MEMBERS_END()
REFLECT_STRUCT_END()

//Reflection for struct FPadding
REFLECT_STRUCT_BEGIN(FPadding)
REFLECT_STRUCT_BEGIN_PARENTS()
REFLECT_STRUCT_PARENT_END()
REFLECT_STRUCT_MEMBERS_BEGIN()
REFLECT_STRUCT_MEMBERS_END()
REFLECT_STRUCT_END()

//Reflection for struct FMargins
REFLECT_STRUCT_BEGIN(FMargins)
REFLECT_STRUCT_BEGIN_PARENTS()
REFLECT_STRUCT_PARENT_END()
REFLECT_STRUCT_MEMBERS_BEGIN()
REFLECT_STRUCT_MEMBERS_END()
REFLECT_STRUCT_END()

//Reflection for struct FBorderRadius
REFLECT_STRUCT_BEGIN(FBorderRadius)
REFLECT_STRUCT_BEGIN_PARENTS()
REFLECT_STRUCT_PARENT_END()
REFLECT_STRUCT_MEMBERS_BEGIN()
REFLECT_STRUCT_MEMBERS_END()
REFLECT_STRUCT_END()
